---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-opentelemetry-collector
  namespace: default
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - events
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-opentelemetry-collector
subjects:
  - kind: ServiceAccount
    name: my-opentelemetry-collector-deployment # replace with your service account name
    namespace: default # replace with your namespace
  - kind: ServiceAccount
    name: my-opentelemetry-collector-daemonset # replace with your service account name
    namespace: default # replace with your namespace
roleRef:
  kind: ClusterRole
  name: my-opentelemetry-collector
  apiGroup: rbac.authorization.k8s.io