mode: daemonset

image:
  repository: otel/opentelemetry-collector-k8s
  tag: 0.123.0

presets:
  logsCollection:
    enabled: true
    includeCollectorLogs: true

resources:
  limits:
    cpu: 250m
    memory: 512Mi