config:
  clients:
    - url: http://loki-gateway.loki/loki/api/v1/push

initContainer:
  - name: init
    image: docker.io/busybox:1.33
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - sysctl -w fs.inotify.max_user_instances=512
    securityContext:
      privileged: true