adminUser: admin
adminPassword: strongpassword

datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.default.svc.cluster.local
      editable: true
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.default.svc.cluster.local
      editable: true
    deleteDatasources:
    - name: Prometheus
    - name: Loki